
export default {
    //Группировка констант по имени
    NAME: 'POSTS_MODULE',

    //setters
    SET_POSTS_DATA: 'SET_POSTS_DATA',
    SET_POST_DATA: 'SET_POST_DATA',

    //getters
    GET_POSTS_DATA: 'GET_POSTS_DATA',
    GET_POST_DATA: 'GET_POST_DATA',

    //actions
    FETCH_POSTS_DATA: 'FETCH_POSTS_DATA',
    FETCH_POST_DATA: 'FETCH_POST_DATA',
    STORE_POST_DATA: 'STORE_POST_DATA',
    UPDATE_POST_DATA: 'UPDATE_POST_DATA',
    DELETE_POST_DATA: 'DELETE_POST_DATA',
}